# Generated by Django 3.1.7 on 2021-03-10 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcat',
            name='slug',
            field=models.SlugField(max_length=25),
        ),
    ]
