# Generated by Django 3.2 on 2021-04-23 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_auto_20210408_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, max_length=135, null=True),
        ),
        migrations.AddField(
            model_name='subcat',
            name='description',
            field=models.TextField(blank=True, max_length=135, null=True),
        ),
    ]
