# Generated by Django 3.1.5 on 2021-01-21 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='%Y/%m/%d')),
                ('alt', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=25, unique=True)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
