# Generated by Django 3.1.5 on 2021-01-21 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('image', '0001_initial'),
        ('category', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('description', models.TextField(max_length=352)),
                ('body', models.TextField(max_length=2048)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('publish_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('عمومی', 'عمومی'), ('پیشنویس', 'پیشنویس')], max_length=8)),
                ('author', models.ForeignKey(default='asghar.a', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.category')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='image.image')),
                ('subcat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.subcat')),
                ('tags', models.ManyToManyField(blank=True, to='tag.Tag')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
