# Generated by Django 3.1.7 on 2021-03-23 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0003_tag_slug'),
        ('article', '0003_auto_20210313_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.TextField(max_length=36000),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='tag.Tag'),
        ),
    ]
