# Generated by Django 3.2 on 2021-04-08 13:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_auto_20210401_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 8, 13, 50, 17, 545003, tzinfo=utc)),
        ),
    ]
