# Generated by Django 3.2 on 2021-04-23 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_alter_article_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='read_time_m',
            field=models.IntegerField(default=3),
        ),
    ]
