# Generated by Django 3.2 on 2021-04-27 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0012_article_read_time_m'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('public', 'public'), ('draft', 'draft')], max_length=8),
        ),
    ]
