# Generated by Django 3.1.7 on 2021-03-22 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0002_remove_tag_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.CharField(default='timezone.now', max_length=25, unique=True),
            preserve_default=False,
        ),
    ]
